interfaces:
  - name: ge-0/0/0
    ip: 10.0.12.1/30
    description: "vSRX-2-link"
  - name: ge-0/0/1
    ip: 10.0.13.1/30
    description: "vSRX-3-link"
  - name: lo0
    ip: 192.168.255.1/32
    description: "Loopback"

ospf_interfaces:
  - ge-0/0/0.0
  - ge-0/0/1.0