interfaces:
  - name: ge-0/0/0
    ip: 10.0.23.2/30
    description: "vSRX-2-link"
  - name: ge-0/0/1
    ip: 10.0.13.2/30
    description: "vSRX-1-link"
  - name: lo0
    ip: 192.168.255.3/32
    description: "Loopback"

ospf_interfaces:
  - ge-0/0/0.0
  - ge-0/0/1.0